### ISSUE TITLE
Install Script Coming Back?

### ISSUE THREAD

**Issue by WarpWing** [atidyshirt/MacOS-Dotfiles#1]
Hi! I was just wondering if I could get an ETA as to when that install script is going to be added back? If at all? No pressure or anything, just curious :)

**Comment by atidyshirt** [comment]
It will be coming back, but it will be probably next week, as I have gone skiing for a week and don't have a laptop. Also once released, please note any issues with it, as there likely will be :).

**Comment by WarpWing** [comment]
> It will be coming back, but it will be probably next week, as I have gone skiing for a week and don't have a laptop. Also once released, please note any issues with it, as there likely will be :).

Ah, well have fun on your skiing trip :)

**Comment by atidyshirt** [comment]
Added a quick installer, its probably not going to work. If you run into problems with it let me know :) (sorry bit new to this types of stuff)

**Comment by WarpWing** [comment]
Don’t worry about. I’m new at this developer stuff too. I’ll make sure to notify you of anything wrong ;)
