### ISSUE TITLE
Some key bindings don't work

### ISSUE THREAD

**Issue by xxxvik-xakerxxx** [atidyshirt/MacOS-Dotfiles#17]
I am trying to use your config on my device but faced difficulties using tmux and cannot figure out how to make its hotkeys work

**Comment by atidyshirt** [comment]
May need a bit more info, is tmux running? If so a few of the bindings have changed.

I need to update the binding list, as a few things have changed, to move between panes, it uses the same bindings as yabai, use leader - v and leader - h to make panes, and ctrl - n and ctrl -p to switch between separate windows. 

The binds can be found in ~/.tmux.conf

**Comment by xxxvik-xakerxxx** [comment]
yes tmux is running what does the leader mean

**Comment by atidyshirt** [comment]
> yes tmux is running what does the leader mean

So the leader key is what key needs to be pressed before the bind, so for mine you press control + space then press v to open a new pane in tmux and control + space (leader key) followed by x to close a pane.

**Comment by xxxvik-xakerxxx** [comment]
oh, okay, I downloaded your configuration again and tmux works, but why is yabai not in tiling by default and how can I switch it there?

**Comment by atidyshirt** [comment]
It should be tiling on spaces 2,3,4,5 not on 6 and 1. Also to change these
you must edit the yabai config file, this should be accessible by typing
'yrc' in terminal if you have copied all my configs, also questions like
this can be answered by using the yabai documentation.

If you are talking about that of space one, it is set to stack, remove that line from ~/.yabairc and you are good to go.

btw, if you look at the files directly you will be able to see these changes if you are familiar with dotfiles :)

**Comment by xxxvik-xakerxxx** [comment]
yes, I have already figured out the setting thanks for the help

**Comment by atidyshirt** [comment]
> yes, I have already figured out the setting thanks for the help

Easy, enjoy the configs
