### ISSUE TITLE
Excessive Homebrew Error Alert in Install.sh

### ISSUE THREAD

**Issue by WarpWing** [atidyshirt/MacOS-Dotfiles#2]
Just a little note that running homebrew processes results in an excessive warning of:

Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

![Screen Shot 2020-07-10 at 12 57 31 PM](https://user-images.githubusercontent.com/28925758/87179621-08bdab00-c2ad-11ea-85a9-603f295969a8.png) 

I don't believe this actually allows the process to run at all. I think that a possible way around it to chmod a  separate script with all the homebrew processes in it.

![Screen Shot 2020-07-10 at 1 00 46 PM](https://user-images.githubusercontent.com/28925758/87179841-66ea8e00-c2ad-11ea-926c-d4d979f626e6.png)

The picture above shows a test.sh file I chmodded and it ran the process with no sudo attached. Seemed to work just fine but again, that's just how I would solve the excessive error. Running the Install Script was fine though other than that. You did a good job though :D

**Comment by atidyshirt** [comment]
Has been committed :), thanks for your help.
