### ISSUE TITLE
Proposal of the Intergration of Cronjobs into the current repository

### ISSUE THREAD

**Issue by WarpWing** [atidyshirt/MacOS-Dotfiles#9]
# Hello Jordan, This is Ty.
# I would like to open up the possibility of intergrating cronjobs into your dotfiles 
# I have listed some reading resources and some example cronjobs in this folder (You can delete this on merge after you have read this :) ) 
# Links 
# https://www.ostechnix.com/a-beginners-guide-to-cron-jobs/

**Comment by atidyshirt** [comment]
Hi Ty, from what I understand cron jobs are used to execute commands on a timer (is this correct)? if so what sort of things are you wanting me to implement on a timer. I previously was using the refreshFrequency parameter to update the bar, however I found this to be very impactful on battery life and switched towards using signals and refresh commands when updating the bar, such as using the bettertouchbar app, when I change volume it also refreshes the bar. 

If  I have misunderstood anything let me know :).

**Comment by WarpWing** [comment]
You understood everything just fine ;) 

I was thinking of making automated like brew updates that cronjobs can run every hour or even daily/weekly/hourly/monthly backups. This is more of a suggestion but I recommend you look into cronjobs, they be very useful 👌

**Comment by atidyshirt** [comment]
I see, that's not a bad idea, I think I have used Cron jobs before on Linux. I will give it a crack, might take a while as I am back at Uni :)

**Comment by WarpWing** [comment]
Btw, you should add some issue labels for organizing your repository stuff like
-Bug
-Resolved
-Open
-Work in Progress
-Idea
-Suggestions

**Comment by WarpWing** [comment]
The suggestion of cronjobs has already been mentioned, we can close it and archive it with the proper label (Suggestion)
